services:
  - type: web
    name: budzy-slack-bot
    env: node
    plan: free
    runtime: node
    buildCommand: "npm ci"
    startCommand: "npm start"
    autoDeploy: true
    envVars:
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_SIGNING_SECRET
        sync: false
    healthCheckPath: /healthz
